application: site-iblv
version: 1
runtime: php55
api_version: 1

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /fonts
  static_dir: fonts
- url: /images
  static_dir: images
- url: /fotos
  static_dir: fotos
- url: /
  script: index.php